### ISSUE TITLE
Please remove extra comma in console.xxx() arguments

### ISSUE THREAD

**Issue by ibc** [mysticatea/event-target-shim#20]
This code (in `src/event.mjs`) fails in Node 6 (parsing error) due to the extra comma in the argument list :

```js
console.error(
                "Unable to preventDefault inside passive event listener invocation.",
                data.passiveListener,  // <-- this comma
            )
```

I've forked the project to remove those commas (there are 2 in total in `src/event.mjs`) and indeed it works in Node 6. But then, when running `npm run lint` it fails with:

```
/Users/ibc/src/forks/event-target-shim/src/event.mjs
  40:14  error  Insert `,`  @mysticatea/prettier
  57:37  error  Insert `,`  @mysticatea/prettier
```

Well, no idea how to reset such a eslint rule. But please, remove it so this good library can be used in Node 6.

**Comment by mysticatea** [comment]
Thank you for the report!

It's definitely a bug. I will fix it.

**Comment by ibc** [comment]
Thanks, will you release a new NPM version soon?

**Comment by mysticatea** [comment]
Yes, I have published!

**Comment by ibc** [comment]
Thanks!
