### ISSUE TITLE
Rollup is emitting non-ES5 build for `dist/event-target-shim.js`

### ISSUE THREAD

**Issue by compulim** [mysticatea/event-target-shim#25]
After rollup build, `dist/event-target-shim.js` is not a ES5 build.

This is verified by looking at https://unpkg.com/event-target-shim@5.0.1/dist/event-target-shim.js. Excerpt from the code:

```js
    privateData.set(this, {
        eventTarget,
        event,
        eventPhase: 2,
        currentTarget: eventTarget,
        canceled: false,
        stopped: false,
        immediateStopped: false,
        passiveListener: null,
        timeStamp: event.timeStamp || Date.now(),
    });
```

You can clearly see `eventTarget` and `event` is emitted in non-ES5 mode and it requires the caller environment to support rest operator. And rest operator is not supported in pure ES5 environment.

All JS files referenced through `package.json/main` field should be ES5. If not, it will break apps that use Webpack in pure ES5 environment, such as `create-react-app`. This is because Webpack assume everything under `node_modules` are precompiled to ES5. For JS files that are not precompiled (ES6+), they are referenced through `package.json/module` field instead.

Should use `@babel/preset-env` with `forceAllTransforms: true` to force the output build as ES5.

**Comment by mysticatea** [comment]
Thank you for this issue.

But I don't have any plan to build this package to ES5.

**Comment by compulim** [comment]
Thanks for your response and sorry for continue on this closed issue.

Your `event-target-shim.umd.js` actually works for ES5, despite it is a UMD but not CJS. I believe the change is minimal. If you agree, I could file a PR for the change in your Rollup config file.

The de facto standard for the JS file referenced by `package.json/main` is ES5. And if the package prefer to expose a ES6+ JS file, it can be referenced by `package/module`.

The problem of having a non-ES5 JS file referenced by `package.json/main` is that:

- Assume you are a web app developer using Webpack or other bundlers
- In your web app, you include a package called `hello-world`
- `hello-world` depends on `event-target-shim`
- As Webpack perform bundling, it assume everything under `node_modules` is pre-built. So Webpack just bundle `event-target-shim` and `hello-world` together in a single file without any transpilations
- The output bundle (a.k.a. monolithic JS file) generated by Webpack will contains non-ES5 code, in this case, rest/spread operator

That means, when someone include `hello-world` package that depends on `event-target-shim`, all in a sudden, their apps will no longer work on browser that does not support rest/spread operator.

This is because during the start of their app, the web app imported `hello-world`, which will load `event-target-shim`. And without rest/spread operator support, the loading of `event-target-shim` will become a syntax error. Syntax error is fatal and stopped everything from loading.

There are few workarounds:

- Configure Rollup to emit ES5 build (using Babel, similar to your `event-target-shim.umd.js` confg)
- Configure `package.json/main` to point to `event-target-shim.umd.js`
   - Optionally configure `package.json/module` to point to `event-target-shim.js`, so bundler can select which one they prefer
- Ask the user who use Webpack, to include the following in their `webpack.config.js`
   - `{ resolve: { alias: { 'event-target-shim': resolve(__dirname, 'node_modules/event-target-shim/dist/event-target-shim.umd.js') } } }`
   - This is for redirecting all `import 'event-target-shim'` call to use `event-target-shim.umd.js` instead
   - This is not quite working because `hello-world` package maintainer is not the web app maintainer. Thus, it sounds weird to ask their users to add this to their Webpack config.

Please consider this issue because:

- UI component developers using your package will be forced to not support browsers that does not work with rest/spread operator
   - The UI component will become less favored because of the browser restrictions
- Web app that use `event-target-shim` as a direct or transient dependencies, will need to update their Webpack config in order to continue enabling their app on older browsers
   - Web app developers are usually not as advanced as UI component developers, they may not know how to update their bundlers to support older browsers and simply drop the UI component instead
