### ISSUE TITLE
constructor should take a single array of strings

### ISSUE THREAD

**Issue by nickdesaulniers** [mysticatea/event-target-shim#3]
Specifically, in the case form the README:
```js
class Foo extends EventTarget("message", "error") {
}
```

This is a problem because what if I have a large number of strings to pass in?  I'm probably going to put them in an array in a previous statement, then pass that array in.  I'll have to use `Function.prototype.apply` in es5, which will break a constructor function! ex:

```js
var events = [
  'negotiationneeded',
  'icecandidate',
  'icecandidateerror',
  'signalingstatechange',
  'iceconnectionstatechange',
  'icegatheringstatechange',
  'connectionstatechange'
];
// oops! this subtly breaks the prototype chain!
RTCPeerConnection.prototype = new EventTarget.apply({}, events);
```

A simple forward compatible change would be to first check if the constructor's `if (arguments.length === 1 && Array.isArray(arguments[0]) { // don't construct a new array`.

**Comment by nickdesaulniers** [comment]
so I would imagine then I could do:
```js
var events = [
  'negotiationneeded',
  'icecandidate',
  'icecandidateerror',
  'signalingstatechange',
  'iceconnectionstatechange',
  'icegatheringstatechange',
  'connectionstatechange'
];
RTCPeerConnection.prototype = new EventTarget(events);
```

**Comment by mysticatea** [comment]
Thank you for the issue.

OK, it sounds reasonable.
I will do it this evening (JST).

**Comment by mysticatea** [comment]
Ah, if there are arguments, a call of `EventTarget(events)` defines new constructor.
So how to use `event-target-shim` in ES5 is below:

```js
//-----------------------------------------------------------------------------
// No attribute listeners.
function Foo() {
    EventTarget.call(this);
}
Foo.prototype = Object.create(EventTarget.prototype, {
    constructor: {
        value: Foo,
        configurable: true,
        writable: true
    },

    //....
});

//-----------------------------------------------------------------------------
// With attribute listeners.
function Foo() {
    EventTarget.call(this);
}
Foo.prototype = Object.create(EventTarget("message", "error").prototype, {
    constructor: {
        value: Foo,
        configurable: true,
        writable: true
    },

    //....
});

//-----------------------------------------------------------------------------
// With attribute listeners as an array.
function Foo() {
    EventTarget.call(this);
}
Foo.prototype = Object.create(EventTarget.apply(null, events).prototype, {
    constructor: {
        value: Foo,
        configurable: true,
        writable: true
    },

    //....
});
```

Now, I'm not sure this enhancement has a value.
I will add documents for ES5.

**Comment by nickdesaulniers** [comment]
That's still not correct.  The use of call/apply on a constructor messes up `this` in the constructor function.

```js
function Foo () { console.log(this) }
new Foo // Object { }
Foo.apply(null, []) // Window
```

**Comment by mysticatea** [comment]
No, `EventTarget(...types)` is a function, not a constructor.
Please see again, `class Foo extends EventTarget("message")` is not `class Foo extends new EventTarget("message")`
 Also, I conformed to work my all example codes.

**Comment by nickdesaulniers** [comment]
wrote a patch for this
