### ISSUE TITLE
listener functions don't HAVE to be functions

### ISSUE THREAD

**Issue by nickdesaulniers** [mysticatea/event-target-shim#6]
they could also be objects with the `handleEvent` method defined on their prototype chain.  [This check](https://github.com/mysticatea/event-target-shim/blob/master/lib/event-target.js#L111-L112) is preventing a consumer of this lib from passing an object to `addEventListener`.

**Comment by mysticatea** [comment]
Thank you for this issue.

Is you meaning that

```js
typeof listener === "object" && typeof listener.handleEvent === "function"
```

should be allowed?

**Comment by mysticatea** [comment]
Yeah, I verified.

![image](https://cloud.githubusercontent.com/assets/1937871/11857385/1c8149d8-a49b-11e5-8f4d-b13bda9a1d07.png)

I'm sorry, I hadn't noticed that.
I will fix that.
